### PR TITLE
Upload File to 0Chain UI and functionality to create wallet, allocation and upload file to allocation.

### PR DESCRIPTION
**Pull request by esliagolli**

### CODE REVIEW

**Comment by shaktals** [comment]
Hey @esliagolli, I see that this is a WIP still. But I'll start giving some feedback.
I see that you are using the `moment` lib, but support for it has been [discontinued](https://momentjs.com/docs/#/-project-status/).
Please consider using alternatives, `date-fns` is one good alternative that I know.

**Comment by esliagolli** [comment]
> Hey @esliagolli, I see that this is a WIP still. But I'll start giving some feedback. I see that you are using the `moment` lib, but support for it has been [discontinued](https://momentjs.com/docs/#/-project-status/). Please consider using alternatives, `date-fns` is one good alternative that I know.

Yep you are right, I was about to fix it because the date shows invalid in that function that I use moment

**Comment by shaktals** [comment]
Hey @esliagolli, I just tried to use the new functionality, but bumped into the following errors:

- first it would complain about an undefined prop in `js-client-sdk`, so I locked the lib to version 1.3.76 and that went away
(the latest version of the lib actually has breaking changes, we need to work on our versioning there)

- then I had trouble building the development bundle because of the latest _optional chaining_ used in wasm.js on `js-client-sdk`, as per [print](https://user-images.githubusercontent.com/24679343/149582261-3d88a866-d261-496a-8b31-7d8e5a3caa17.png). I tried adding the `gatsby-optional-chaining` plugin, but it didn't solve it.
Then I manually removed the optional chaining from wasm.js at node_modules, and got pass this. But we should fix the build flow.

- upon successfully running the app, now when clicking on `Upload file to 0chain` I get:

`Uncaught (in promise) Error: bls is undefined  _callee3$ index.tsx:32`

Selection_309

Looking up the trace, I see:
Selection_310

I tried to console.log `RestApiManager` being initialized, but it seems like the hook at Web3 is not being called somehow. Can you inspect and let me know? I'll try again tomorrow.

**Comment by shaktals** [comment]
Locking the `js-client-sdk` version to 1.3.72 solved the issues above.

**Comment by shaktals** [comment]
I was able to successfully publish a data set using the Rinkeby network.
Some issues I saw:

- 'sample data' should be a different file, as it's optional no need to use that right now
- I was able to successfully upload the file and publish it, but after reloading the app, I couldn't see it on the profile tab

Also some other details to tweak:
- after reloading the `Publish` page, the `File` field automatically loaded the previous file uploaded to 0chain
- if I try to submit the form with new data, it asks 'Please select a file' on the `Upload file to 0chain` field, that should not be required

Let's have a call about this, looking good!

**Review by shaktals — APPROVED** [review]

**Pull request merged**
